### ISSUE TITLE
Run whether users are logged in or not - inconsistencies.

### ISSUE THREAD

**Issue by gyoza** [chef-cookbooks/windows#263]
Hello,
This code

Using 1.36.0, 1.36.1, 1.38.1 all exhibit this behavior. 

```
windows_task "Chef Client Run Every Hour to check for cookbooks." do 
    cwd "C:\\opscode\\chef\\bin"
    command "powershell.exe -noprofile -noexit -executionpolicy Bypass 'Start-Process C:\\opscode\\chef\\bin\\chef-client.bat'"
    frequency :minute 
    frequency_modifier 60
    action :create
    run_level :highest
end 
```

On a windows 10 system running chef 12.4.1 the scheduled task gets created properly with "run whether user is logged in or not"

On Windows 2008 R2 this does not get set and I am unable to see why.. 

Any ideas why this is occurring? There are no errors displayed in the chef-client log.. Thanks for your time.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
