### ISSUE TITLE
windows_task will not 'notify' other resources

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/windows#271]
If you have a scheduled task, and you attempt to delete it with ':delayed' it will never be deleted. 

Example

```
  windows_task 'foobar' do
    user "example.com\\bob"
    command  "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -noexit -executionpolicy Bypass -File c:\foo.ps1 '"
    action [:create,:run]
    notifies :end, 'windows_task[foobar]', :delayed  #TODO This strangely never gets deleted
    notifies :delete, 'windows_task[foobar]', :delayed #TODO This strangely never gets deleted
    run_level :highest
    force true
  end
```

Windows 2012 R2
Chef 12.4.1
Windows cookbook 1.38.1

**Comment by spuder** [comment]
Better workaround is to make the delete as part of the action. 

        action [:create,:run,:delete]

**Comment by chrisgit** [comment]
Hi, my response is late but I hope this helps someone out.

If the windows_task resource task_name attribute is not specified then the task_name is defaulted to the resource name. Therefore in your example windows_task 'foobar' is the name of the resource and also the task_name.

In load_current_resource the task_name is changed (see below)
`
pathed_task_name = @new_resource.task_name[0, 1] == '\\' ? @new_resource.task_name : @new_resource.task_name.prepend('\\')
`

The @new_resource.task_name.prepend('\\') is adding two slashes to the @resource.task_name. Normally in Ruby when the underlying object is changed a method is marked with a bang to signify warning, it's not obvious but prepend appears to change the underlying object.

When the windows_task LWRP has finished executing if there were any actions the Chef::Runner will try and locate the resource in the resource queue to establish whether it should also action any notifications. My belief is that the name of the resource has changed and now includes two backslashes (\\), the resource cannot be found in the resource queue, which is why the notifications are failing.

Can you try your code specifying the task_name and making it different from the resource name, e.g
`
windows_task 'install_foobar' do
    task_name 'foobar'
    user "example.com\\bob"
    command  "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -noexit -executionpolicy Bypass -File c:\foo.ps1 '"
    action [:create,:run]
    notifies :end, 'windows_task[install_foobar]', :delayed
    notifies :delete, 'windows_task[install_foobar]', :delayed
    run_level :highest
    force true
  end
`

**Comment by spuder** [comment]
Thanks for the response. I see now that the reason this happens is because the resource name is not the same as the task name. 


So basically the following will fail to send notifications

```ruby
windows_task 'chef ad-join' do
  user 'SYSTEM'
  command 'chef-client'
  notifies :create, 'file[c:/notifytest.txt]', :immediately #Not working
  action :create
end
```

Where as this will work properly

```ruby
windows_task 'chef ad-join' do
  task_name 'foobar'
  user 'SYSTEM'
  command 'chef-client'
  notifies :create, 'file[c:/notifytest.txt]', :immediately #Not working
  action :create
end
```

I still think a change needs to be made to the cookbook since this is an easy trap to fall into (It bit me twice). The task_name parameter needs to be made mandatory.

**Comment by chrisgit** [comment]
Thanks for confirming. It's a bug in the windows_taks resource, the resource name gets changed in load_current_resource hence why Chef::Runner can't locate resources in the notification queue. I can't make any fixes at the moment as we don't have a CLA.

The error is to do with the use of the prepend method, this changes the underlying object, e.g

x = 'hello'
y = x.prepend('\\')
x #=> \\hello
y #=> \\hello

**Comment by spuder** [comment]
If i'm understanding correctly, String.prepend in ruby creates another object. So the solution might be to change [this line](https://github.com/chef-cookbooks/windows/blob/master/providers/task.rb#L157): 

     pathed_task_name = @new_resource.task_name[0, 1] == '\\' ? @new_resource.task_name : @new_resource.task_name.prepend('\\')

to something like this? 

```ruby
if @new_resource.task_name[0, 1] == '\\' do
  @new_resource.task_name
else
  new_name = "\\#{@new_resource.task_name}"
  @new_resource.task_name = new_name
end
```

This is just a stab in the dark. I'll need to do more testing. I do have an CLA so if this works, i'll open a pull request.

**Comment by mwrock** [comment]
wow. You'd think `prepend` should be `prepend!`.

**Comment by spuder** [comment]
:+1:  Manually verified against edee5a7 confirmed working
