### ISSUE TITLE
vagrant box listed in .kitchen.yml not available

### ISSUE THREAD

**Issue by xacaxulu** [chef-cookbooks/windows#290]
I cloned this project and immediately ran `chef exec kitchen converge` while being logged into HashiCorp via `vagrant login`. This is the error message:

STDERR: The box 'chef/windows-server-2008r2-standard' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

Where are these vagrant boxes located?

**Comment by mwrock** [comment]
The default test-kitchen behavior is to grab them from the [bento box project](https://github.com/chef/bento) and most of the linux distros are public on atlas. Unfortunately what wuindows bento boxes there are are private since chef does not have rights to distribute windows images. However, there are public boxes on atlas you could swap in if you wanted. For instance manu of my `.kitchen.yml` files have this:

```
platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2
```

If you are interested in making your own windows vagrant boxes with packer, have a look at [this post](http://www.hurryupandwait.io/blog/creating-windows-base-images-for-virtualbox-and-hyper-v-using-packer-boxstarter-and-vagrant) and also check out this [great walk through](https://learn.chef.io/local-development/windows/get-started-with-test-kitchen/) of test-kitchen/windows development work flows.

**Comment by xacaxulu** [comment]
@mwrock Thanks for the detailed info, I appreciate it.
