### ISSUE TITLE
Batch Elevated?

### ISSUE THREAD

**Issue by styk-tv** [chef-cookbooks/windows#331]
Hi,

Is it possible to run batch in elevated mode when UAC is disabled? Any ideas on how to accomplish this? Perhaps would be good to add an "elevated" attribute.

Scenario: Administrator account is disabled,  userX is in administrators group, UAC is disabled, batch runs with lowest elevation. Cannot by default accomplish elevation to run commands that require higher level of access.

**Comment by mwrock** [comment]
How are you kicking off the chef client. if userX is an administrator even with UAC off, you should be elevated running it from a shell you started "as administrator.

**Comment by BBK-PiJ-2015-14** [comment]
Hi Matt @mwrock 

Using "batch" from windows cookbook. Kickoff from Kitchen Converge. Chef-Zero provisioner and WinRm transport on Win7 (although omnibus takes over). userX as in Administrators group, UAC is disabled. 

I'm resurrecting old prunsrv java service. I can replicate problem on actual box (using userX regular console, service installs but not starting due to missing registry entries, using same user elevated shell, service installs and starts as proper registry entries are written prior to start). So my original issue remains, if I could make sure that chef windows "batch" runs as elevated then issue would be non existent. I probably tried like 20 different scripts for self-elevating of shell. Obviously I could just run everything as Administraotr but that would be cheating right? (administrator user is disabled by default on my image)

**Comment by BBK-PiJ-2015-14** [comment]
FYI @mwrock So I just found this https://github.com/test-kitchen/test-kitchen/issues/876

**Comment by Annih** [comment]
Hello @BBK-PiJ-2015-14 

Can you give more détails of your kitchen test or the batch resource that fails to converge?

Regards,

Annih

**Comment by mwrock** [comment]
Sorry I just left a comment in https://github.com/test-kitchen/test-kitchen/issues/876#issuecomment-175613399 but reading this for the second time I am not sure you are using the provisioner discussed there: https://github.com/smurawski/chef-zero-scheduled-task the chef zero scheduled task provisioner. That is what you want to use.

**Comment by styk-tv** [comment]
Had to recompile chef-zero-scheduled-task provisioner myself. gem install was actually pulling wrong version. Now withlatest everyting works. Case closed.
