### ISSUE TITLE
'windows_task' should have a parameter attribute to specify how long a task can run before it should terminate.

### ISSUE THREAD

**Issue by joshoohaah** [chef-cookbooks/windows#353]
right now there is no way in the LWRP resource to specify how long a task can run before it should terminate.  currently, it defaults to 3 days (see image): 
![image](https://cloud.githubusercontent.com/assets/8366405/14048626/836f6f32-f27d-11e5-9c5f-461bd60c4896.png)

This has double use then as the `chef_client` cookbook could also consume this feature, along with an interval/splay for this task.

**Comment by NimishaS** [comment]
Added `execution_time_limit` option in https://github.com/chef/chef/pull/5886. It accepts time in seconds e.g. `execution_time_limit '60'`.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
