### ISSUE TITLE
Allow chef_gem resources to specify a local file system path

### ISSUE THREAD

**Issue by bandrews-apartments** [chef-cookbooks/windows#360]
Hi Chef Windows team,

We have situations where we will be unable to reach out to rubygems.org to install the default.rb gem installations.  Without access to rubygems.org, Chef mostly cannot run with the windows cookbook as a dependency.

(recipes/default.rb)
`%w( win32-api win32-service ).each do |win_gem|
  chef_gem win_gem do
    options '--platform=mswin32'
    action :install
    compile_time false if respond_to?(:compile_time)
  end
end

%w( windows-api windows-pr win32-dir win32-event win32-mutex ).each do |win_gem|
  chef_gem win_gem do
    action :install
    compile_time false if respond_to?(:compile_time)
  end
end`

I'm wondering if you can add a variable on these to use a specified "local path" attribute that would allow the gems to be installed from the local file system instead of reaching out to the internet to get them installed.  If this attribute is not specified, then just go out to the internet to grab the gems.

**Comment by mwrock** [comment]
you could change the default gem source on the node to point to an internal rubygems repository.  If setting up an alternate gem repo is not an option for you. You may be better off ensuring that your base image has these gems installed and then omit the inclusion of the default recipe.

**Comment by chrisgit** [comment]
You can use the source method of chef_gem https://docs.chef.io/resource_chef_gem.html

````
source
    Ruby Type: String
    Optional. The path to a package in the local file system
````

We also did not want to use Rubygems.org and identified two common types of usage for gems
* Gems that are installed to support the code inside the cookbooks (e.g. chef-sugar)
* Gems that are installed to support the role of the node on the network (e.g. sinatra)

For the first scenario we vendored the Gems by including them in the cookbooks and setting Rubys $LOAD_PATH to the location of the Gem in the cookbook, thus avoiding installing the gem as per https://sethvargo.com/using-gems-with-chef/ 

In the end we vendored gems in some of our cookbooks and installed them using Bundler but it is awkward, particularly as chef_gem runs at compile time (so that it will satisfy the situation where the gem is used in the cookbook). 

Unfortunately we couldn't set the gem sources from https://rubygems.org/ to nothing because Test Kitchen downloads a fresh Busser gem so our CI would fail.

As part of a spike into securing our Gems we looked at hosting our own Gem server using
* Artifactory
* Gem server (comes with Gem but requires Gems to be installed)
* Gem mirror
* Gem in a box
* Gem fury

However, I agree with Matt Wrock, were possible it's best to ensure that the base image contains the Gems - although I'm sure there will be the occasional community cookbook that slips through the net and decides to install a Gem that isn't already on your gold image.

**Comment by tas50** [comment]
These gem installs have been removed since they're actually built into the Chef client now. If you need anything else you can accomplish it with a chef_gem install in your own cookbook and you can modify sources there.
