### ISSUE TITLE
Allow windows_task to end task

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/windows#361]
### Cookbook version

1.38.0
windows 2012r2
### Scenario:

The ":delete" action on the windows_task resource is not idempotent

Arguably this is a windows limitation. But the cookbook should be able to work around it. 
### Steps to reproduce:

Create a scheduled task by hand. Then create a resource to end and delete the task. It will work the first time, but not the second time. 

``` ruby
 windows_task 'DelArchivedIISLogs' do
   action [:end, :disable, :delete]
 end
```

``` ruby
    Errno::ENOENT
    -------------
    No such file or directory - windows_task[DelArchivedIISLogs]: task does not exist, cannot end

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows/providers/task.rb:120:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/nd-web/recipes/schedtasks.rb

     68: windows_task 'DelArchivedIISLogs' do
     69:   action [:end, :disable, :delete]
     70: end
     71:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/nd-web/recipes/schedtasks.rb:68:in `from_file'

    windows_task("DelArchivedIISLogs") do
      action [:end, :disable, :delete]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_task
      cookbook_name "nd-web"
      recipe_name "schedtasks"
      task_name "DelArchivedIISLogs"
    end

    Platform:
    ---------
    x64-mingw32
```

**Comment by chrisgit** [comment]
This might be desired functionality of the task resource?

Available actions are :create, :run, :change, :delete, :end, :enable, :disable of those actions :end and :enable will throw errors if the schedule task does not exist. However there are some validation methods that will also throw exceptions.

Arguably the :end action should probably just warn? We'd be looking for guidance from the developers one of the Chef employees here to understand intent. @mwrock ?

In order to complete your Chef run without changing the underlying Task resource you would have to guard the end with not_if or only_if; the code you will require would be the same code as the Task resource already does so you'd be duplicating your effort (you can co-erce the provider by injecting in the resource but it is not very nice so I do not recommend it)

````
task = windows_task 'end task' do
    task_name 'DelArchivedIISLogs'
        action :end
        only_if do
	    prov = Chef::Provider::WindowsTask.new task, nil
            prov.load_current_resource
            prov.current_resource.exists
    end
 end
 
 windows_task 'disable and delete' do
    task_name 'DelArchivedIISLogs'
    action [:disable, :delete]
 end
````
My view is if the resource code be changed to warn for the :end action that would be best?

**Comment by mwrock** [comment]
Not really an "intention" that this is as it is. This is a flaw in the resource.

**Comment by chrisgit** [comment]
Thanks @mwrock Would you be looking for someone to make some subtle changes to this resource to warn instead of throw in the case of the :end action?

Also I've been asked a few times about the option of providing an import action for task, I see it has been mentioned on an issue somewhere too. However, unless this is a one time import it might be quite difficult comparing any current resource against the one defined in a recipe?

**Comment by mwrock** [comment]
A PR for the warning would be great @chrisgit . An `:import` sounds interesting. We'd definitely want it to be idempotent but that should be in a separate PR if you decided to tackle that.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
