### ISSUE TITLE
not able to install silently WinPcap_4_1_3.exe

### ISSUE THREAD

**Issue by ranraq** [chef-cookbooks/windows#396]
### Cookbook version

12
### Chef-client version

12
### Platform Details

Windows 2012 R2
### Scenario:

I am trying to install winpcap silently on wndows 2012 r2 server. i used below code.
windows_package "winpcap" do
    source location
    options '/q'
    installer_type :inno
    action :install

end

But its asking for user intervention to complete the installation like click next.. How can i install silently the software?

**Comment by mwrock** [comment]
Its likely that installer needs more than just `/q`. The best way to troubleshoot is to simply use `MSIEXEC` and fine what switches generate a silent install and then plug those into the options.

**Comment by christianclarke** [comment]
Hello ranraq.

The reason why winpcap is failing is because the installer in question does not support silent installs.  WinPcap used to support silent installations - but it was removed due to "misuse".

Do you need winpcap installed because you wish to use wireshark ?  If so, for network packet tracing in wireshark, installation of winpcap isn't actually necessary.  What is necessary is the installation of network packet filter driver which is inside the winpcap installer.

I've written a cookbook which installs wireshark and/or it installs the network packet tracing driver out of the Winpcap binary - without having to install winpcap.  I shall be open-sourcing this cookbook onto NVM labs github site once it has undergone abit more testing and internal review.

Hopefully, by sometime next week.
