### ISSUE TITLE
windows_task doesn't support commands redirections in command property

### ISSUE THREAD

**Issue by jugatsu** [chef-cookbooks/windows#426]
When using command redirections https://ss64.com/nt/syntax-redirection.html in command property windows_task becomes not idempotent.
Considerer example from chef-client cookbook
https://github.com/chef-cookbooks/chef-client/blob/master/recipes/task.rb#L43
```
chef-client .... ^> NUL 2^>^&1
```
This is because windows_task parses command from schtasks.exe /XML output for idempotence.
https://github.com/chef-cookbooks/windows/blob/master/providers/task.rb#L188
But xml output of ^> transforms to `&gt;` and so & to `&amp;`

Steps to reproduce:
Just include chef-client::task and converge multiple times. Windows task `chef-client` will be created on each run.

**Comment by jugatsu** [comment]
https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
