### ISSUE TITLE
chef dsc_resource to set the dns address for Windows nodes

### ISSUE THREAD

**Issue by Pcchef** [chef-cookbooks/windows#464]
Hello,
I am new to Chef automation and am trying to set the DNS primary and secondary address to windows nodes using chef xNetworking dsc_resource and I have a show stopper with defining Interface alias.
Different nodes have different ethernet adapter names. How do I define the Interface alias now to run dsc configuration on a set of nodes. I did define address family and address in attributes file. 

Here is my dsc_resource code:

dsc_resource 'config_dns' do
  resource :xDnsServerAddress
  module_name 'xNetworking'
  property :AddressFamily, node['addressfamily']
  property :InterfaceAlias, node['interfacealias']
  property :Address, [node['primary'], node['secondary']]
end

**Comment by smurawski** [comment]
@Pcchef Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the [Chef mailing lists](https://discourse.chef.io), [Chef Community Slack](http://community-slack.chef.io), or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
