### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by Tech356** [chef-cookbooks/windows#492]
Starting with cookbook version 3.1.1, testing on Windows 7 has been dropped.

https://github.com/chef-cookbooks/windows/commit/ca6a71f42f1cb43213d6bfc9b76e9a58c3571809

RFC 021 still states that Window 7 is supported by the Chef Client. 

https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md

Why was testing on Windows 7 dropped? Is Windows 7 support being removed from this cookbook?

**Comment by iennae** [comment]
In general, the Chef Cookbooks do not follow the Chef RFC https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md. Windows 7 is EOL. While it's still supported, it's not tested with this cookbook as it will take too long to iterate across changes to test against Windows 7 and Windows 10.

**Comment by Tech356** [comment]
I am confused, Windows 7 is EOL? Microsoft says it is supported until [January 14, 2020](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).

**Comment by tas50** [comment]
By EOL we mean no longer in Mainstream Support with Microsoft. I'd really like to stress that this is just about being able to test the full cookbook in under a workday locally. We constantly have to weigh the suites due to the time they take to run. Windows 7 will continue to run just fine, but in terms of testing Windows 10 is a priority at this point.

**Comment by Tech356** [comment]
That makes sense. Thanks for the clarification.
