### ISSUE TITLE
No keys found for certificate

### ISSUE THREAD

**Issue by chrisdrobison** [chef-cookbooks/windows#526]
### Cookbook version
3.4.4

### Chef-client version
13.7.16

### Platform Details
AWS Windows Server 2012 R2 and 2016

### Scenario:
Import a PFX into the my local machine store.

### Steps to Reproduce:
This is the recipe:

windows_certificate 'D:\ServiceFabricSetup\servicefabricdevclusterserver.pfx' do
    pfx_password 'password'
    store_name "MY"
end

### Expected Result:
To be able to manage the private keys, but they apparently don't exist after they are imported.

### Actual Result:

It says are there are keys,

![image](https://user-images.githubusercontent.com/1816289/36169557-c7911416-10b9-11e8-8cab-c62f7ca53eb4.png)

But, when I go to manage them, I get this.

![image](https://user-images.githubusercontent.com/1816289/36169591-dd36e82c-10b9-11e8-9f53-e9b40dbfa6b2.png)

**Comment by ilovemysillybanana** [comment]
Did you ever find a solution for this? I’m currently having this issue as well.

**Comment by chrisdrobison** [comment]
Sucks, but after scouring the internet, that is only example I was able to find that actually worked in chef.

**Comment by tas50** [comment]
@chrisdrobison Can you give this a try with the latest version of the cookbook? In 4.3.0 we entirely rewrote how certificates work and it would be worth tracking this down within the new codebase if it's still an issue.

**Comment by chrisdrobison** [comment]
Yeah, I'll try it out next Monday.

**Comment by tas50** [comment]
This should be resolved in the latest version of the cookbook which uses and updated version of our win32-certstore gem. If you're still having this issue after updating the cookbook then please open this back up so we can dig in.

**Comment by sean-horn** [comment]
The identical issue happens when using `windows_certificate` from Chef Client 15.4.45 and 16.1.16 with no windows cookbook in the runlist.

I have two certs that have imported seemingly successfully. They can be viewed in windows tools.

* One test PFX cert produced from the private windows root CA of a customer. This one ships with the full chain. After import, the private keys cannot be managed, Right clicking the cert and choosing the option to "Manage Private Keys" results in "No keys found", as above.

* And then another test PFX cert produced with openssl. In fact ANY cert produced by a third-party provider is ok. This one is just a self-signed cert and after import, the private keys can be managed.
