### ISSUE TITLE
Can't find dism features in node attributes anymore.

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/windows#542]
### Cookbook version
4.0.1

### Chef-client version
13.8.5

### Platform Details
Windows 2012r2 and Windows2016

### Scenario:
I'm not seeing the windows features that are installed in the node attributes on chef-server or chef-automate like before when they were cached in ohai

### Steps to Reproduce:
create server with windows cookbook in run list

### Expected Result:
windows features showing up in node attributes on chef-server and chef-automate

### Actual Result:
no errors just don't see feautes in node attributes.

**Comment by tas50** [comment]
@Stromweld 4.0 entirely changed up how the caching works. Previously it was done with an ohai plugin that had the side effect of giving users access to the feature data. I looked at porting this ohai plugin into Ohai itself, but since microsoft uses different names for features on dism and powershell it didn't seem to make sense to bring that into core Chef. If you want to continue to have that data available on nodes you can just add that plugin to a cookbook and ship it out to your nodes.
