### ISSUE TITLE
windows_feature stop supporting Win2008r2 server  

### ISSUE THREAD

**Issue by binpath** [chef-cookbooks/windows#547]
### Cookbook version
Since 4.1.0 to 4.1.3

### Chef-client version
chef-client 12.21.3 or 13.8.5 is the same result

### Platform Details
Windows2008 R2
### Scenario:
 `windows_feature 'FS-NFS-Services' do
       action :install
       install_method :windows_feature_powershell
  end`

ERROR:
windows_feature_powershell[FS-NFS-Services] (C:/chef/cache/cookbooks/windows/resources/feature.rb line 47) had an error: RuntimeError: The Windows feature FS-NFS-Services is not available on this version of Windows. Run 'Get-WindowsFeature' to see the list of available feature names.

### Steps to Reproduce:
The error is that in resource feature_powershell.rb you changed the **available** method to:

```
def parsed_feature_list
    # Grab raw feature information from dism command line
    raw_list_of_features = if node['os_version'].to_f < 6.2
                             powershell_out!('Import-Module ServerManager; Get-WindowsFeature | Select-Object -Property Name,InstallState | ConvertTo-Json -Compress', timeout: new_resource.timeout).stdout
                           else
                             powershell_out!('Get-WindowsFeature | Select-Object -Property Name,InstallState | ConvertTo-Json -Compress', timeout: new_resource.timeout).stdout
                           end

    Chef::JSONCompat.from_json(raw_list_of_features)
  end
```

and `powershell_out!('Import-Module ServerManager; Get-WindowsFeature | Select-Object -Property Name,InstallState | ConvertTo-Json -Compress', timeout: new_resource.timeout).stdout`

brings the InstallState Property with null, example:
`"[{\"Name\":\"AD-Certificate\",\"InstallState\":null},{\"Name\":\"ADCS-Cert-Authority\",\"InstallState\":null},`......

### Expected Result:
The InstallState Property comes with a number:
`{\"Name\":\"NET-WCF-HTTP-Activation45\",\"InstallState\":0}`

`parsed_feature_list.each do |feature_details_raw|
      case feature_details_raw['InstallState']
      when 5 # matches 'Removed' InstallState
        add_to_feature_mash('removed', feature_details_raw['Name'])
      when 1, 3 # matches 'Installed' or 'InstallPending' states
        add_to_feature_mash('enabled', feature_details_raw['Name'])
      when 0, 2 # matches 'Available' or 'UninstallPending' states
        add_to_feature_mash('disabled', feature_details_raw['Name'])
      end
    end`

### Actual Result:
Chef client stops because of the result of changing the way to parse if the feature is available to if is removed, Install.

**Comment by tas50** [comment]
So this is a two fold issue:

First we technically don't support Windows 2008 R2 for Chef anymore. We're actively doing our best not to break it, but we don't test for it anymore as mainstream support from Microsoft ended Jan 2015. Yes there's extended support until 2020, and that's why we're doing our best not to entirely break things until 2020. This is pretty similar to what we did with Windows 2003, where we just last month removed all the crazy code necessary to support it.

The second part is that windows_feature_powershell resource *should* still work on Windows 2008 R2, but it will require a mildly modern version of PowerShell to function. Powershell 2.0 that shipped with WIndows 2008 R2 is severely lacking in functionality and supporting that would cripple our ability to move forward with Chef. Now that we're using converto-json in the powershell you'll need at least PowerShell 3.0. I have a ticket open already against the chef client to get a more friendly failure warning in this resource.

Going forward in the chef client we're going to start converting a lot of resources over to our new faster powershell exec helper. This requires PowerShell 3.0 since it also uses the converto-json cmdlet. Converting these resources gives us a 7x performance boost since we don't have to constantly spawn off powershell.exe processes and then parse the string output of those cmdlets. So you're really going to need to upgrade to a modern powershell or remain on an older version of chef-client and cookbooks.

**Comment by tas50** [comment]
So I have some code locally that I'll get out tonight, but this will be the error you'll receive on PS < 3.0

```
﻿﻿           ================================================================================
           Error executing action `remove` on resource 'windows_feature[Remove FTP for Appveyor]'
           ================================================================================

           RuntimeError
           ------------
           windows_feature_powershell[Remove FTP for Appveyor] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb line 47) had an error: RuntimeError: The windows_feature_powershell resource requires PowerShell 3.0 or later. Please install PowerShell 3.0+ before running this resource.
```
